# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: AWS authenticate
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
#        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
#        role-duration-seconds: 1200
#        role-session-name: MySessionName

    - name: AWS Deploy
      run: |
        aws s3 cp README.md s3://$AWS_ARTIFACT_BUCKET_NAME/swissbank_$GITHUB_REF.md
